-- Nexys4 harness for the generated IIR filter.
-- Hold BTNC to record from the microphone (the speaker is muted). On release,
-- the recording plays back on a loop through the filter core to the audio jack.
-- SW0 up bypasses the filter (LED0 lights). SW1 up adds hiss before the filter.
-- LED1-15 show the microphone level, 6 dB per LED. CPU_RESET resets the design.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity nexys4_top is
  generic (RECORD_MS : natural := 4000);  -- longest recording in ms (up to about 5000)
  port (
    CLK100MHZ  : in  std_logic;
    CPU_RESETN : in  std_logic;
    BTNC       : in  std_logic;
    SW         : in  std_logic_vector(1 downto 0);
    LED        : out std_logic_vector(15 downto 0);
    M_CLK      : out std_logic;
    M_DATA     : in  std_logic;
    M_LRSEL    : out std_logic;
    AUD_PWM    : out std_logic;
    AUD_SD     : out std_logic);
end entity;

architecture rtl of nexys4_top is
  signal rst_sync   : std_logic_vector(1 downto 0) := "11";
  signal rst        : std_logic;
  signal sw_meta    : std_logic_vector(1 downto 0) := "00";
  signal sw_s       : std_logic_vector(1 downto 0) := "00";
  signal btn_meta   : std_logic := '0';
  signal btn_s      : std_logic := '0';
  signal mic        : signed(15 downto 0);
  signal strobe     : std_logic;
  signal playback   : signed(15 downto 0);
  signal lfsr       : std_logic_vector(15 downto 0) := x"ACE1";
  type history_t is array (0 to 4) of signed(15 downto 0);
  signal white      : history_t := (others => (others => '0'));
  signal source     : signed(15 downto 0) := (others => '0');
  signal filtered   : std_logic_vector(15 downto 0);
  signal audio      : signed(15 downto 0) := (others => '0');
  signal pwm_cnt    : unsigned(10 downto 0) := (others => '0');
  signal pwm_duty   : unsigned(10 downto 0) := (others => '0');
  signal pwm        : std_logic := '0';
  signal peak, held : unsigned(15 downto 0) := (others => '0');
  signal peak_cnt   : unsigned(12 downto 0) := (others => '0');
begin
  -- Synchronise the reset button, the record button and the switches
  process (CLK100MHZ)
  begin
    if rising_edge(CLK100MHZ) then
      rst_sync <= rst_sync(0) & not CPU_RESETN;
      sw_meta  <= SW;
      sw_s     <= sw_meta;
      btn_meta <= BTNC;
      btn_s    <= btn_meta;
    end if;
  end process;
  rst <= rst_sync(1);

  u_mic : entity work.pdm_mic
    port map (clk => CLK100MHZ, rst => rst, m_clk => M_CLK, m_data => M_DATA,
              sample => mic, strobe => strobe);
  M_LRSEL <= '0';

  u_rec : entity work.recorder
    generic map (MAX => RECORD_MS * 48828 / 1000)
    port map (clk => CLK100MHZ, en => strobe, rec => btn_s, din => mic, dout => playback);

  -- The filter core generated by HDL Coder. Its clock enable pulses once per
  -- sample, so it advances one sample every 2048 clock cycles.
  -- (To run the original filter instead, generate it and use work.iir_original.)
  u_filter : entity work.iir_pipelined
    port map (clk => CLK100MHZ, reset => rst, clk_enable => strobe,
              x => std_logic_vector(source), ce_out => open, y => filtered);

  process (CLK100MHZ)
    variable hiss  : signed(17 downto 0);
    variable noisy : signed(17 downto 0);
  begin
    if rising_edge(CLK100MHZ) then
      -- White noise: a 16-bit LFSR, stepped every clock so samples are uncorrelated
      lfsr <= lfsr(14 downto 0) & (lfsr(15) xor lfsr(13) xor lfsr(12) xor lfsr(10));

      if strobe = '1' then
        -- Keep the last 5 white-noise samples
        white(0) <= signed(lfsr);
        for i in 1 to 4 loop
          white(i) <= white(i-1);
        end loop;

        -- Filter input: the playback, plus hiss if SW1 is up. The hiss is white noise
        -- minus itself 4 samples earlier, which removes the low frequencies and
        -- peaks at 6 kHz. The shift sets its level: each step down is 6 dB louder.
        if sw_s(1) = '1' then
          hiss  := shift_right(resize(white(0), 18) - resize(white(4), 18), 4);
          noisy := resize(playback, 18) + hiss;
          if noisy > 32767 then
            source <= to_signed(32767, 16);
          elsif noisy < -32768 then
            source <= to_signed(-32768, 16);
          else
            source <= noisy(15 downto 0);
          end if;
        else
          source <= playback;
        end if;

        -- Output: silent while recording, otherwise filtered or bypassed
        if btn_s = '1' then
          audio <= (others => '0');
        elsif sw_s(0) = '1' then
          audio <= source;
        else
          audio <= signed(filtered);
        end if;

        -- Peak microphone level over each 8192 samples (0.17 s)
        peak_cnt <= peak_cnt + 1;
        if peak_cnt = 0 then
          held <= peak;
          peak <= unsigned(abs(mic));
        elsif unsigned(abs(mic)) > peak then
          peak <= unsigned(abs(mic));
        end if;
      end if;
    end if;
  end process;

  -- 11-bit PWM at 48.828 kHz
  process (CLK100MHZ)
  begin
    if rising_edge(CLK100MHZ) then
      pwm_cnt <= pwm_cnt + 1;
      if pwm_cnt = 0 then
        pwm_duty <= unsigned(not audio(15) & std_logic_vector(audio(14 downto 5)));  -- offset binary
      end if;
      if pwm_cnt < pwm_duty then pwm <= '1'; else pwm <= '0'; end if;
    end if;
  end process;

  AUD_PWM <= pwm;
  AUD_SD  <= '1';                           -- enable the audio amplifier

  LED(0) <= sw_s(0);
  meter : for k in 1 to 15 generate         -- LED k lights when the level reaches 2^(k-1)
    LED(k) <= '1' when held(15 downto k-1) /= 0 else '0';
  end generate;
end architecture;
